version: '2'

volumes:
  nextcloud:

services:
  app:
    build: .
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
      #- ./data:/var/www/html/data
      - ./apps:/var/www/html/apps2:rw
