version: '2'

volumes:
  nextcloud:

services:
  app:
    build: .
    ports:
      - 8080:80
    volumes:
      - nextcloud:/var/www/html
      #- ./data:/var/www/html/data
      - ./apps/contacts:/var/www/html/apps2/contacts:rw
      - ./apps/vueexample:/var/www/html/apps2/vueexample:rw

